Task 4.5 ImageFormSet
thinknetica-django-lab-04/azoriy pull request #49
Opened 2021-08-11 16:00 UTC by azoriy

Closes #25

2021-08-13 07:35 UTC, inkviz96 requested changes

2021-08-13 07:35 UTC, inkviz96 commented on app/main/models.py
>                                      default="default",
У вас связанная модель, значит ее значение будет другая модель, а вы ставите дефолтное значение строка

2021-08-14 09:31 UTC, morgangt approved these changes

2021-08-14 09:31 UTC, morgangt commented on app/main/views.py
> +            images.save()
В случае успешного прохождения валидация формы стоит показывать пользователю другую страницу или выводить сообщение (можно сделать например через контекст)
Просто сейчас у вас получается что после успешной валидации формы нечего не происходит пользователь не видит ни какого результата

2021-08-15 12:31 UTC, merged